### ISSUE TITLE
AnyIO 2.0 support and new release

### ISSUE THREAD

**Issue by agronholm** [tzickel/justredis#1]
I'd love to see this project reach a release stage. If you need help migrating it to the AnyIO 2.0 API, I can probably do that. Beyond that, how much more work do you suppose this needs until you're ready to release?

**Comment by mjwestcott** [comment]
@tzickel Thanks for your work on this project. The async Redis situation is pretty dire at the moment, since both https://github.com/aio-libs/aioredis and https://github.com/NoneGG/aredis have gone 6 months without maintenance. It's also brilliant that you support AnyIO. Do you plan to continue working on this?

**Comment by tzickel** [comment]
Fixed, the other stuff for release is documented in the README roadmap.
